/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CourseFile: typeof import('./src/components/CourseFile.vue')['default']
    CoursePhoto: typeof import('./src/components/CoursePhoto.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LessonFIle: typeof import('./src/components/LessonFIle.vue')['default']
    PhotoUser: typeof import('./src/components/PhotoUser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserFile: typeof import('./src/components/UserFile.vue')['default']
  }
}
