/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/AboutUs': RouteRecordInfo<'/AboutUs', '/AboutUs', Record<never, never>, Record<never, never>>,
    '/Comments': RouteRecordInfo<'/Comments', '/Comments', Record<never, never>, Record<never, never>>,
    '/Courses': RouteRecordInfo<'/Courses', '/Courses', Record<never, never>, Record<never, never>>,
    '/ExamAns': RouteRecordInfo<'/ExamAns', '/ExamAns', Record<never, never>, Record<never, never>>,
    '/Language': RouteRecordInfo<'/Language', '/Language', Record<never, never>, Record<never, never>>,
    '/Lessons': RouteRecordInfo<'/Lessons', '/Lessons', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/Rating': RouteRecordInfo<'/Rating', '/Rating', Record<never, never>, Record<never, never>>,
    '/Ratings': RouteRecordInfo<'/Ratings', '/Ratings', Record<never, never>, Record<never, never>>,
    '/TeacherForStudent': RouteRecordInfo<'/TeacherForStudent', '/TeacherForStudent', Record<never, never>, Record<never, never>>,
    '/Test': RouteRecordInfo<'/Test', '/Test', Record<never, never>, Record<never, never>>,
    '/Useraccount': RouteRecordInfo<'/Useraccount', '/Useraccount', Record<never, never>, Record<never, never>>,
    '/UserCourse': RouteRecordInfo<'/UserCourse', '/UserCourse', Record<never, never>, Record<never, never>>,
    '/UserLesson': RouteRecordInfo<'/UserLesson', '/UserLesson', Record<never, never>, Record<never, never>>,
    '/UserTeacher': RouteRecordInfo<'/UserTeacher', '/UserTeacher', Record<never, never>, Record<never, never>>,
  }
}
