/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/AboutUs': RouteRecordInfo<'/AboutUs', '/AboutUs', Record<never, never>, Record<never, never>>,
    '/AdminDashboard': RouteRecordInfo<'/AdminDashboard', '/AdminDashboard', Record<never, never>, Record<never, never>>,
    '/Ans': RouteRecordInfo<'/Ans', '/Ans', Record<never, never>, Record<never, never>>,
    '/Certificate': RouteRecordInfo<'/Certificate', '/Certificate', Record<never, never>, Record<never, never>>,
    '/Comments': RouteRecordInfo<'/Comments', '/Comments', Record<never, never>, Record<never, never>>,
    '/Courses': RouteRecordInfo<'/Courses', '/Courses', Record<never, never>, Record<never, never>>,
    '/eg': RouteRecordInfo<'/eg', '/eg', Record<never, never>, Record<never, never>>,
    '/Exam': RouteRecordInfo<'/Exam', '/Exam', Record<never, never>, Record<never, never>>,
    '/ExamAns': RouteRecordInfo<'/ExamAns', '/ExamAns', Record<never, never>, Record<never, never>>,
    '/Language': RouteRecordInfo<'/Language', '/Language', Record<never, never>, Record<never, never>>,
    '/Lessons': RouteRecordInfo<'/Lessons', '/Lessons', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/Quiz': RouteRecordInfo<'/Quiz', '/Quiz', Record<never, never>, Record<never, never>>,
    '/Rating': RouteRecordInfo<'/Rating', '/Rating', Record<never, never>, Record<never, never>>,
    '/Ratings': RouteRecordInfo<'/Ratings', '/Ratings', Record<never, never>, Record<never, never>>,
    '/Registration': RouteRecordInfo<'/Registration', '/Registration', Record<never, never>, Record<never, never>>,
    '/StudentDetails': RouteRecordInfo<'/StudentDetails', '/StudentDetails', Record<never, never>, Record<never, never>>,
    '/TeacherForStudent': RouteRecordInfo<'/TeacherForStudent', '/TeacherForStudent', Record<never, never>, Record<never, never>>,
    '/TeacherOverviewCourse': RouteRecordInfo<'/TeacherOverviewCourse', '/TeacherOverviewCourse', Record<never, never>, Record<never, never>>,
    '/Useraccount': RouteRecordInfo<'/Useraccount', '/Useraccount', Record<never, never>, Record<never, never>>,
    '/UserCourse': RouteRecordInfo<'/UserCourse', '/UserCourse', Record<never, never>, Record<never, never>>,
    '/UserLesson': RouteRecordInfo<'/UserLesson', '/UserLesson', Record<never, never>, Record<never, never>>,
    '/UserQuiz': RouteRecordInfo<'/UserQuiz', '/UserQuiz', Record<never, never>, Record<never, never>>,
    '/UserTeacher': RouteRecordInfo<'/UserTeacher', '/UserTeacher', Record<never, never>, Record<never, never>>,
  }
}
